apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: db
data:
  dbName: postgres-db
  pgdata: /var/lib/postgresql/data

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: db
data:
  username: cm9vdA==
  password: cm9vdA==
